name: covid19
channels:
  - bioconda
  - defaults
dependencies:
  - beagle-lib=3.1.2
  - iqtree=1.5.5
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libgcc=4.8.5
  - libgfortran=3.0.1
  - libtool=2.4.6
  - mpi=1.0
  - mrbayes=3.2.7
  - muscle=3.8.1551
  - ncurses=6.1
  - openjdk=8.0.152
  - openmpi=4.0.2
  - readline=8.0
  - zlib=1.2.11

