name: covid19
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - beagle-lib=3.1.2
  - ca-certificates=2020.1.1
  - iqtree=1.6.12
  - libcxx
  - libcxxabi
  - libgcc=4.8.5
  - libgfortran
  - libtool=2.4.6
  - mpi=1.0
  - mrbayes=3.2.7
  - muscle=3.8.1551
  - ncurses=6.1
  - openjdk=8.0.152
  - openmpi=4.0.2
  - openssl=1.1.1
  - readline=8.0
  - wget=1.20.1
  - zlib=1.2.11

